# Generated by Django 4.1.1 on 2022-09-19 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fsq_id', models.CharField(max_length=24)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('region', models.TimeField()),
                ('name', models.TextField()),
            ],
        ),
    ]
