# Generated by Django 4.1.1 on 2022-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.TextField(),
        ),
    ]
